apiVersion: batch/v1
kind: Job
metadata:
  name: example-6
spec:
  # ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        args: ["echo helloworld"]
      restartPolicy: Never
